const stages = ["UNDERSTAND", "DEFINE", "DESIGN", "PLAN", "IMPLEMENT", "VERIFY", "REVIEW", "SIMPLIFY", "COMPLETE"];

export default function Home() {
  return <>
    <a className="skip" href="#main">Skip to content</a>
    <header className="site-header"><a className="brand" href="#top"><span>DK</span> Development Kit</a><nav aria-label="Primary"><a href="#framework">Framework</a><a href="#integrations">Integrations</a><a href="#install">Install</a><a href="#safety">Safety</a></nav><a className="mini-cta" href="https://github.com/eybersjp/development-kit">GitHub ↗</a></header>
    <main id="main">
      <section className="hero" id="top"><div className="eyebrow"><i aria-hidden="true" /> Development Kit Framework · v0.6.0</div><h1>Ship software with<br/><em>discipline, not drift.</em></h1><p className="lede">A guarded development framework for AI coding agents. Turn intent into verified software through a lifecycle that keeps humans in control.</p><div className="actions"><a className="button primary" href="#install">Start building <span>→</span></a><a className="button secondary" href="https://github.com/eybersjp/development-kit">View on GitHub ↗</a></div><dl className="stats"><div><dt>14</dt><dd>commands</dd></div><div><dt>18</dt><dd>specialist agents</dd></div><div><dt>45</dt><dd>skills</dd></div><div><dt>4</dt><dd>guardrail hooks</dd></div></dl></section>

      <section className="workflow" id="framework"><div className="section-head"><span>01 / THE SYSTEM</span><h2>One path from idea<br/>to evidence.</h2><p>Every phase has a purpose. Every transition has a gate. Work moves forward only when its current promise is proven.</p></div><div className="pipeline" aria-label="Development lifecycle">{stages.map((stage,i)=><div className="stage" key={stage}><b>{String(i+1).padStart(2,"0")}</b><strong>{stage}</strong>{i<stages.length-1&&<span aria-hidden="true">→</span>}</div>)}</div></section>

      <section className="contrast"><div className="drift"><span>WITHOUT THE FRAMEWORK</span><h2>Prompt. Patch.<br/>Hope.</h2><ul><li>Requirements mutate mid-build</li><li>Agents skip straight to code</li><li>“Done” means unverified</li><li>Context drifts between tasks</li></ul></div><div className="discipline"><span>WITH DEVELOPMENT KIT</span><h2>Intent. Evidence.<br/>Confidence.</h2><ul><li>Specification before implementation</li><li>Small, independently testable tasks</li><li>Fresh specialists with clear boundaries</li><li>Verification before completion</li></ul></div></section>

      <section className="features"><div className="section-head"><span>02 / BUILT-IN DISCIPLINE</span><h2>Structure for serious<br/>agentic work.</h2></div><div className="card-grid"><article><i aria-hidden="true">⌁</i><h3>Guided workflows</h3><p>Use <code>/dk-autopilot</code> for the full lifecycle or focused commands for research, design, build, test, review, and ship.</p></article><article><i aria-hidden="true">◎</i><h3>Specialist agents</h3><p>Architecture, implementation, testing, security, accessibility, and review are handled by specialists with one clear job.</p></article><article><i aria-hidden="true">◇</i><h3>Verification gates</h3><p>Acceptance criteria exist before code. Failures stop the task loop. Completion follows evidence, never optimism.</p></article><article><i aria-hidden="true">∿</i><h3>Ponytail simplicity</h3><p>A strict ladder favors reuse and native capability before adding code, abstractions, dependencies, or providers.</p></article><article><i aria-hidden="true">⊕</i><h3>External research</h3><p>Current evidence can inform decisions, but retrieved content stays untrusted and can never override project rules.</p></article><article><i aria-hidden="true">▣</i><h3>Human approval</h3><p>Installs, provider writes, configuration changes, and other consequential actions wait at explicit approval gates.</p></article></div></section>

      <section className="platforms" id="integrations"><p>WORKS WHERE YOUR TEAM WORKS</p><div>{["Antigravity","OpenCode","Claude Code","Cursor","VS Code / Copilot","Cline","Windsurf"].map(x=><span key={x}>{x}</span>)}</div></section>

      <section className="install" id="install"><div><span>03 / INSTALL</span><h2>One command.<br/>Your environment.</h2><p>Install the complete framework or target the coding agent your team already uses. Existing adapter files are preserved by default.</p><a href="https://github.com/eybersjp/development-kit#installation">Read installation docs →</a></div><div className="terminal"><div className="terminal-top"><span>QUICK START</span><i aria-hidden="true">● ● ●</i></div><pre><code><b># Antigravity — auto-detect and install</b>{'\n'}<strong>npx development-kit init</strong>{'\n\n'}<b># OpenCode — rules and all compatible skills</b>{'\n'}<strong>npx development-kit init --opencode</strong>{'\n\n'}<b># All five cross-platform adapters</b>{'\n'}<strong>npx development-kit init --all-platforms</strong>{'\n\n'}<b># Inspect changes before writing</b>{'\n'}<strong>npx development-kit init --all --dry-run</strong></code></pre></div></section>

      <section className="safety" id="safety"><div className="shield">DK<span>GUARDED</span></div><div><span>04 / TRUST BOUNDARIES</span><h2>Autonomy,<br/>with a seatbelt.</h2><p>Development Kit lets agents do substantial work without quietly expanding their authority. Web pages, provider output, and retrieved documents are evidence—not instructions.</p><div className="rules"><p><b>01</b> External content stays untrusted</p><p><b>02</b> Consequential actions require approval</p><p><b>03</b> Credentials never enter the repository</p><p><b>04</b> Tests gate every completion claim</p></div></div></section>

      <section className="final"><span>READY WHEN YOU ARE</span><h2>Build like the outcome<br/>actually matters.</h2><p>Give your AI coding agents the same thing strong engineering teams rely on: process, boundaries, and proof.</p><div className="actions"><a className="button primary" href="#install">Install Development Kit →</a><a className="button secondary light" href="https://github.com/eybersjp/development-kit">Explore the repository ↗</a></div></section>
    </main>
    <footer><a className="brand" href="#top"><span>DK</span> Development Kit</a><p>Open source · MIT License · v0.6.0</p><div><a href="https://github.com/eybersjp/development-kit">GitHub</a><a href="https://github.com/eybersjp/development-kit/tree/main/docs">Documentation</a></div></footer>
  </>;
}
